### ISSUE TITLE
Werckerを使った自動テスト、デプロイの実行

### ISSUE THREAD

**Issue by syui** [ArchLinuxJP/archlinuxjp.github.io#1]
このリポジトリの別ブランチ`branch:source`に`push`した時に、それを察知し、`branch:master`にデプロイするように設定したいのですが、権限がなくリポジトリがWerckerに追加できません。対応していただければ嬉しいです。

こちらの設定ができるような権限を与えていただければ、それが可能になると思われます。

https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/

Werckerを使った自動テスト及び、デプロイの実行によるプロジェクトのメリットは、メンバーが手軽にブログを更新できるようになることです。

**Comment by kusakata** [comment]
言われた通り、サードパーティのアクセスの制限を解除しました。

**Comment by syui** [comment]
一応、設定とテストが完了しました。ビルド及び、デプロイのログは、Publicにしてありますが、確認いただけるのなら、何らかの秘匿されるべき情報が漏れている場合は教えてほしいと思います。

Wercker Passed BOT 7:23 PM [ArchLinuxJP/archlinuxjp.github.io](https://app.wercker.com/#applications/56713855d1bd86764902afc3) [deploy3a3c0c95](https://app.wercker.com/#deploy/56713b4cd1bd86764902b65f) of source to archlinuxjp.github.io by syui passed

この点については、Privateにも設定できますが、どちらに設定するか悩みます。

**Comment by kusakata** [comment]
了解しました。

**Comment by syui** [comment]
@kusakata 気に入らないところはレイアウトだろうがなんだろうが遠慮なく直していってください。基本的に、`source`ブランチに`push`すれば変更が反映されると思います。
