### ISSUE TITLE
Hugoにテンプレートとして登録する

### ISSUE THREAD

**Issue by syui** [ArchLinuxJP/archlinuxjp.github.io#4]
現在、元となるテンプレートが原形を留めてないので、元テンプレートは、謝辞として著作者を明示した上で、新たなテンプレートとして `Hugo Theme` に登録し、 `Footer(フッター)` の表記においてもそのテンプレート(新)に表記を変更する予定です。

新テンプレートは、 `archlinuxjp/hugo-theme-archlinux` のリポジトリで作成する予定で、その際、テンプレート自体をどういった方向で作成するのかなど、意見がある方は書いてください。

```
© 2016 Arch Linux JP.
- Powered by Hugo. Theme by hugo-icarus-theme. 
+ Powered by Hugo. Theme by hugo-theme-archlinux. 
```

個人的には、すべて英語に直した上で、メニューに載せるURLなども変換するのが良いかと思っています。また、ロゴやタイトルは、本家に似せた形に変更しようと考えています。

なぜなら、コンセプトとして、 `archlinux` サイトの `Hugo` 版みたいな感じで考えているからです。予想される問題や意見があれば、承ります。

**Comment by kusakata** [comment]
Arch Linux サイトの Hugo 版とは www.archlinux.org の機能・外観を完全に模倣するということですか？
当初の構想どおり運営者のブログと運営するなら、必要ないと思います。

**Comment by syui** [comment]
いや、模倣という目的では全く無く、従来の外観などをどのように変更すれば使いやすくなるかの実験サイト、参考サイトとしても機能します。

もちろん、運営者のブログとしても機能します。

また、ArchWikiに投稿しようかどうしようか躊躇してるものをテスト投稿する場所としても機能させたいとも個人的には考えています。特にこれは、投稿を外部から受ける際の書式、形式に関しても、ある程度の推測を促す目的もあります。

**Comment by kusakata** [comment]
実験・参考サイトとして作るなら、archlinuxjp.github.io とは別のサイトにするか、あるいは今のブログを別のところに移すべきだと思います。
www.archlinuxjp.org のトップページとほとんど同じものが運営者ブログという形であるとサイトの構成上冗長ですし閲覧者も混乱するかと。
もちろん、「新しい実験サイトを作りました」という記事をトップページのニュースやブログに載せて紹介する、あるいは新デザイン・ベータ版へのリンクという形で従来のウェブサイト内に入れるのは良いです。

ArchWiki についてのアイデアは ArchWiki に投稿するのが一番筋が通っているのではないでしょうか。
ArchWiki に投稿するのがためらわれる内容、あるいは敷居が高いというなら個人ブログや Qiita などを使うのが適していると思います。また、そういうサイトの内容を収集するものとして Arch Planet も存在するわけですし。

**Comment by syui** [comment]
## 前提

> www.archlinuxjp.org と全く同じものを作る意味はありません。

既にご理解されていると思いますが、全く同じものを作る目的ならば、ドロップダウンメニューなどは追加しません。

混乱するというのはたしかにそうかもしれませんが、現時点での初期段階においては、仕方ないと思っています。投稿や変更を繰り返していくうちに、変化していくものではないでしょうか。

そして、本ブログがレイアウト上どのように機能する可能性があるのかというのは、本Issuesとはあまり関係がありません。この件に関しては、後述します。

## 本題

本題に関しては要約すると3つのポイントがあります。

- 元のテーマとはかけ離れてしまっているので、新しいテーマとして作成した上で、フッターなどの表記を変更するかどうか。

- 新しいテーマとして作成した場合、Hugoテーマとして登録できるので、それに登録するかどうか。

- 新しいテーマとして登録する場合、言語やレイアウトなどを変更するかどうか。変更するとしたら、どのように変更するかなど。

本Issuesは、この点についてとなっております。

## 機能や役割について

あまり関係ない話になっていしまいますが、本ブログの機能や役割についてです。

具体的な機能や役割については、運営者のブログです。

なぜなら、コミットできるのがメンバーに限られているからです。これは、先程も述べましたが前提の話です。

### 類似性

初期のレイアウトは似せて作りましたが、そこからどういう風に変えていくかを念頭に置いているため、初期段階では類似点が多くあります。

投稿や変更を繰り返していくうちに、変化させていくつもりではあります。

しかし、これについては、本件がテンプレートとしての保存等の有無に関する話であり、テンプレートをどのように活用できるか、具体的には、テンプレートして保存するか否か、登録するか否か、登録するとしたらどのようなレイアウトで登録するかということを主題にしました。したがって、本ブログの機能や役割についての話ではありませんが、類似性はブログとしての役割が増していくと同時に、減少していくと思います。

### ArchWikiとの関連性

転載や使い回しのことを考えれば、ArchWikiの書式に合わせて書いてもらったほうがよいかもしれない、そのように考えていますので、そう書きましたが、現時点では、これは機能するものではありません。

「投稿したい人がいれば、受け入れます」という感じですが、これも前提の話で、「ArchWiki についてのアイデアは ArchWiki に投稿するのが一番筋が通っている」と誰もがそう考えることだろうと思われます。

初期段階では、ここで述べたものが機能することは少ないでしょう。

全く関係のない個人的な話になりますが、私は、ArchWikiの書式を意識して、投稿していこうかなと考えました。なぜなら、ArchWikiのほうでも使い回しができて一石二鳥かもしれませんので。

現在、色々なことを考えています。そして、その役割や機能が確固たるものになるのは、割りと先の話かもしれないので、とりあえず色々なことをやってみる方向で考えている感じです。

## 本題の目的

本Issuesを立てたのは、あまり確固とした目的なんかはないわけですが、色々な取組をやる一つとして、テーマを作って登録してみると、なにか反応あるかもしれないなーと思いましたので、立てました。

## 結論

しかし、やらないほうがよさそうだと先ほど考えなおしましたので、Hugoにテンプレートとして登録するありません。

長くなりましたが、ご意見ありがとうございます。
